# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stashy < Formula
  desc "Self-hosted file storage service"
  homepage "https://github.com/stashysh/stashy"
  version "0.5.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.4/stashy_0.5.4_darwin_amd64.tar.gz"
      sha256 "5e2fc78591be17a9ed6d4e11074a2c82d8d04b1f7d0d610c50b0b997ceadeddb"

      define_method(:install) do
        bin.install "stashy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.4/stashy_0.5.4_darwin_arm64.tar.gz"
      sha256 "f73530d1109722677bc1827ee974a01d6296a17001f5b4f863ea3bd03dc6c87c"

      define_method(:install) do
        bin.install "stashy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.4/stashy_0.5.4_linux_amd64.tar.gz"
      sha256 "ccda4a48c12532e1dd28b9230b344576af08eaa3f15a5c75a8ff8d166e2ce7fc"
      define_method(:install) do
        bin.install "stashy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.4/stashy_0.5.4_linux_arm64.tar.gz"
      sha256 "da127cb03e71e8cc540d372306257b0ce10a7a1358e9a42145e44f194bc37a47"
      define_method(:install) do
        bin.install "stashy"
      end
    end
  end
end
