# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stashy < Formula
  desc "Self-hosted file storage service"
  homepage "https://github.com/stashysh/stashy"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.3/stashy_0.5.3_darwin_amd64.tar.gz"
      sha256 "2b5bcac916937463b2c41f67139be3d0e4aae79d878dea8367d8eec41a028626"

      define_method(:install) do
        bin.install "stashy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.3/stashy_0.5.3_darwin_arm64.tar.gz"
      sha256 "4fb1b6ade08e44a421335f068fb454cc117c0fcd82c5a45088a04ea8a2412fcb"

      define_method(:install) do
        bin.install "stashy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.3/stashy_0.5.3_linux_amd64.tar.gz"
      sha256 "0a41f4fbf7657890139d5ad30d273520e29b82a844505143a6a55745fdd52a6b"
      define_method(:install) do
        bin.install "stashy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stashysh/stashy/releases/download/v0.5.3/stashy_0.5.3_linux_arm64.tar.gz"
      sha256 "8d12c52a2160fd7317f08e8ee31f5255cfbabc27198255c33c401c700a8a28e2"
      define_method(:install) do
        bin.install "stashy"
      end
    end
  end
end
