# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stashy < Formula
  desc "Self-hosted file storage service"
  homepage "https://github.com/stashysh/stashy"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stashysh/stashy/releases/download/v0.4.0/stashy_0.4.0_darwin_amd64.tar.gz"
      sha256 "7796f411de399b0574b1bd2f6793c768846924b6eea8600079b1630a63ecdaf5"

      define_method(:install) do
        bin.install "stashy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stashysh/stashy/releases/download/v0.4.0/stashy_0.4.0_darwin_arm64.tar.gz"
      sha256 "e8b5f6b1740b1e0a1f7babbb28335c8af8ae4207404d14600f3652509f06a711"

      define_method(:install) do
        bin.install "stashy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stashysh/stashy/releases/download/v0.4.0/stashy_0.4.0_linux_amd64.tar.gz"
      sha256 "f45bcde1f9c19fcf9debe097f7d3bd29cf8c128090cbd2142a2bdad16e43e3e2"
      define_method(:install) do
        bin.install "stashy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stashysh/stashy/releases/download/v0.4.0/stashy_0.4.0_linux_arm64.tar.gz"
      sha256 "faea53559abd36a64cfc45a6af4888faa721e4a865353ecda67cf3c4ca3e2df5"
      define_method(:install) do
        bin.install "stashy"
      end
    end
  end
end
